
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1234
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: CarShop1_development

est:
  <<: *default
  database: CarShop1_test


production:
  database: betonnalavka_prod
  url: <%= ENV['DATABASE_URL'] %>
